// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkfyhmbcogmhypxylghr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZnlobWJjb2dtaHlweHlsZ2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTgzMzAsImV4cCI6MjA2MjEzNDMzMH0.wZIsx4TaCSTpdWUYht2TWYjb7i1KvvtaQPz6WX2_cbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);